security:
  pi_pin: "1193"

feature_flags:
  enable_pi: true
  enable_solaris: true
  enable_games: true
  enable_media: true
  enable_power: true

idle:
  menu_seconds: 60           # idle in menu -> relock
  external_seconds: 60       # idle in mpv/games/vnc -> kill app and return to menu

ui:
  title: "SPARCstation"
  fps: 60
  font_size: 54
  small_font_size: 28

paths:
  lock_py: "/home/pi/sparc_lock/puzzle_lock.py"
  launch_solaris_sh: "/home/pi/sparc_lock/launch_solaris.sh"
  mpv_input_conf: "/home/pi/sparc_lock/mpv.input.conf"

  media_root: "/home/pi/sparc_media"
  media_images: "/home/pi/sparc_media/images"
  media_music: "/home/pi/sparc_media/music"
  media_videos: "/home/pi/sparc_media/videos"

  games_root: "/home/pi/sparc_games/installed"

logs:
  shell_log: "/home/pi/sparc_lock/logs/kiosk_shell.log"
  mpv_log: "/home/pi/sparc_lock/logs/mpv.log"
  solaris_log: "/home/pi/sparc_lock/logs/solaris_vnc.log"
  games_log_dir: "/home/pi/sparc_lock/logs/games"
